### ISSUE TITLE
Suggestions for including proto files in installation

### ISSUE THREAD

**Issue by chekanov** [decibelcooper/proio#126]
We need to include "model" mc.proto and other template files inside created PROIO files.
 Therefore, I would suggested to copy the directory "model" to the installation location. Then one can link such files using the path $PROIO/model/mc.proto (as an example) during file creation of files.

There should be also a mechanism to store such files (and log files) inside PROIO

best, Sergei

**Comment by decibelcooper** [comment]
Hi Sergei (@chekanov), thanks!  My thought is that File Descriptor protos are included in generated code, so in a sense these files are already being installed.  There is also significant overlap here with #20.  If we satisfy #20 and add the ability to dynamically deserialize unknown messages using the stored File Descriptor protos, does this satisfy your requirements?

**Comment by chekanov** [comment]
Hi, David

 Yes, this should work if this can be used for reading files with unknown data model.

**Comment by decibelcooper** [comment]
Hi Sergei (@chekanov),

Indeed this is the plan.  I will close this issue in favor of #20, since this should be seen before closing that issue.
