### ISSUE TITLE
Failed to compile using singularity

### ISSUE THREAD

**Issue by chekanov** [decibelcooper/proio#5]
Hi, David

 I've typed "make", and after 5 min of dong something with the singularity  container, it failed to compile 
 ```
Importing: /tmp/singularity-cache/docker/sha256:1024a55a68004f50fe1cfdb2c6353faeadc033c343d632c8e198091901bcfc45.tar.gz
/bin/tar: opt/Go/.wh..wh..opq: implausibly old time stamp 1969-12-31 18:00:00
Importing: /tmp/singularity-cache/metadata/sha256:90a76215fbf315cbb77cb867de4eaf6e7bc8b44ea70ddf6bab70378ab8ea112f.tar.gz
Done. Container is at: proio-gen.img
singularity exec -C -H /proio proio-gen.img protoc --gofast_out=go-proio/model proio.proto
ERROR  : Base home directory does not exist within the container: /users
ABORT  : Retval = 255
make: *** [go-proio/model/proio.pb.go] Error 255
```
Is it possible to have an option for cpp version using make, assumed gcc is installed?

**Comment by decibelcooper** [comment]
Hi Sergei,

The Makefile in the root directory is only for generating the protobuf code when the data model has changed.  This is not required to build the cpp library, and for that there is a standard cmake build.  Please see the README.md in https://github.com/decibelcooper/proio/tree/master/cpp-proio.

That being said, what environment are you running make in?  Whatever it is, it is returning /proio for $PWD.  This is strange.  If you would like to modify the data model and generate the code with the Makefile, please place the repository in a subdirectory of your $HOME.
